<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Version>1.0.0</Version>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<EnableHarmony>true</EnableHarmony>
		<EnableModZip>true</EnableModZip>
		<ModZipPath>$(ProjectDir)releases</ModZipPath>
		<EnableModDeploy>true</EnableModDeploy>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Framework\Assets\**" />
	  <Compile Remove="releases\**" />
	  <EmbeddedResource Remove="Framework\Assets\**" />
	  <EmbeddedResource Remove="releases\**" />
	  <None Remove="Framework\Assets\**" />
	  <None Remove="releases\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<None Update="manifest.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	
	<ItemGroup>
		<ContentPacks Include="Content Packs\[CP] Parchment" Version="$(Version)" IgnoreModFilePatterns="\.aseprite$" />
	</ItemGroup>
</Project>
